# Generated by Django 5.1.5 on 2025-02-06 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.CharField(max_length=255)),
                ("value", models.FloatField()),
                ("day_of_week", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Showcase",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("expenses", models.JSONField(default=list)),
                ("budgets", models.JSONField(default=list)),
                ("final_cost", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="UserAdmin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField()),
                ("telephone", models.CharField(max_length=15)),
                ("function", models.CharField(max_length=255)),
                ("permissions", models.JSONField()),
                ("is_global_user", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CourseClass",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ribalta.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExperimentalStudent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField()),
                ("telephone", models.CharField(max_length=15)),
                (
                    "experimental_classes",
                    models.ManyToManyField(to="ribalta.courseclass"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="courseclass",
            name="experimental_students",
            field=models.ManyToManyField(to="ribalta.experimentalstudent"),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField()),
                ("telephone", models.CharField(max_length=15)),
                ("total_value", models.FloatField()),
                ("discount", models.FloatField()),
                ("due_date", models.DateField()),
                ("courses", models.ManyToManyField(to="ribalta.course")),
                ("showcases", models.ManyToManyField(to="ribalta.showcase")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="showcase",
            name="student_cast",
            field=models.ManyToManyField(to="ribalta.student"),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("paid_value", models.FloatField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("pix", "Pix"),
                            ("debito", "Débito"),
                            ("credito", "Crédito"),
                            ("money", "Dinheiro"),
                        ],
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateField()),
                ("pay_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Pago"),
                            ("is_due_date", "Vence hoje"),
                            ("in_debt", "Atrasado"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ribalta.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(to="ribalta.student"),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PRESENT", "Presente"), ("ABSENT", "Ausente")],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "course_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ribalta.courseclass",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ribalta.student",
                    ),
                ),
            ],
        ),
    ]
